---
title: "world-proj-illustration"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(projWiz)
library(ggplot2)
library(terra)

world_lonlat = terra::rast(world_shaded_relief)
ext(world_lonlat) <- c(-180,180,-90,90)
crs(world_lonlat) <- "epsg:4326"

world_lonlat[1:360,c(1,1:12 * 60),1:3] <- 0
world_lonlat[c(1,1:6 * 60),1:720,1:3] <- 0

quick_proj_world_map <- function(proj_type, title, crop=FALSE) {
  # sometimes in polar araes will generate error, need to crop
  if (crop) {
    world_lonlat = crop(world_lonlat, ext(-180, 180, -86, 86))
  }
  world_lonlat |> 
    terra::project(proj_world(proj_type,0), mask=TRUE,method="average") |> 
    plotRGB(main=title)
}
```


```{r, fig.width=10, fig.height=5, dpi = 300}
par(mfrow=c(1,2))
quick_proj_world_map(world_proj_list$equal_area$point_polar$Mollweide,"Mollweide")
quick_proj_world_map(world_proj_list$equal_area$point_polar$Hammer_Aitoff,"Hammer Aitoff")
```

remove `world_proj_list$equal_area$line_polar$Wagner_VII`
```{r, fig.width=15, fig.height=5, dpi = 600}
par(mfrow=c(1,3))
quick_proj_world_map(world_proj_list$equal_area$line_polar$Equal_Earth,"Equal Earth")
quick_proj_world_map(world_proj_list$equal_area$line_polar$Eckert_IV,"Eckert IV")
quick_proj_world_map(world_proj_list$equal_area$line_polar$Wagner_IV,"Wagner IV")
```

```{r, fig.width=15, fig.height=5, dpi = 300}
par(mfrow=c(1,3))
quick_proj_world_map(world_proj_list$compromise$round_boudnary$Robinson,"Robinson")
quick_proj_world_map(world_proj_list$compromise$round_boudnary$Winkel_Tripel,"Winkel Tripel",TRUE)
quick_proj_world_map(world_proj_list$compromise$round_boudnary$Natural_Earth,"Natural Earth",TRUE)
```
```{r, fig.width=15, fig.height=5, dpi = 300}
par(mfrow=c(1,3))
quick_proj_world_map(world_proj_list$compromise$rectangular$Miller_cylindrical_I,"Miller cylindrical I",TRUE)
quick_proj_world_map(world_proj_list$compromise$rectangular$Patterson,"Patterson")
quick_proj_world_map(world_proj_list$compromise$rectangular$Plate_Carrée,"Plate Carrée")
```

